# System API Endpoints
global.financial.account.api.host=localhost
global.financial.account.api.port=8081

credit.card.api.host=localhost
credit.card.api.port=8081

salesforce.financial.api.host=localhost
salesforce.financial.api.port=8081

# HTTP Configuration
http.port=8082
http.host=0.0.0.0

# Anypoint MQ Configuration
anypoint.mq.url=https://mq-us-east-1.anypoint.mulesoft.com/api/v1/
anypoint.mq.clientId=a212dedae89f4da79b836c23764bb993
anypoint.mq.clientSecret=69b5404C76C1448B91A9c69a1f441845
