# System API Endpoints
global.financial.account.api.host=localhost
global.financial.account.api.port=8081

credit.card.api.host=localhost
credit.card.api.port=8081

# HTTP Configuration
http.port=8082
http.host=0.0.0.0

